spec:
  inputs:
    weekly:
      type: boolean
      default: false
      description: "Flag to be defined in schedules so that the low-periodicity jobs can know whether to run."

---

default:
  image: python:3.13
  tags:
    - dind
    - inasset

  cache:
    key: cache-default
    paths:
      - .cache

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

stages:
  - prepare
  - test
  - build
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

include:
  - project: 'wjs/wjs-profile-project'
    ref: 'wjs-develop'
    file: '.gitlab-ci-pre-commit.yml'
  - project: 'wjs/wjs-profile-project'
    ref: 'wjs-develop'
    file: '.gitlab-ci-pkg-build-and-upload.yml'


# Build an image with all dependencies needed by yakunin
build-base-image:
  stage: prepare
  image: docker:dind
  services:
    - docker:dind
  variables:
    TAG: $CI_REGISTRY/wjs/yakunin-project/yakunin:$ML_VERSION
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull $TAG || true
    - docker build --cache-from $TAG --tag $TAG --build-arg ML_VERSION=$ML_VERSION -f Dockerfile.base .
    - docker push $TAG
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - if: ($CI_PIPELINE_SOURCE == "schedule") && ("$[[ inputs.weekly ]]" == "true")
      when: on_success
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true # (the pipeline continues running even if the manual job is not run)

# Update/upgrade the base image with latest debian security updates
apt-update:
  stage: deploy
  image: docker:dind
  tags:
    - inasset
    - dind
  services:
    - docker:dind
  variables:
    TAG: $CI_REGISTRY/wjs/yakunin-project/yakunin:$YAKUNIN_VERSION
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull $TAG || true
    - docker build --cache-from $TAG --tag $TAG --build-arg=ML_VERSION=$ML_VERSION --file Dockerfile .
    - docker push $TAG

  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true # (the pipeline continues running even if the manual job is not run)


run-tests:
  stage: test
  tags:
    - fast-test
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: always
  image: $CI_REGISTRY/wjs/yakunin-project/yakunin:$ML_VERSION
  script:
    - pytest -v -n 16


pre-commit:
  extends:
    - .run-pre-commit
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: always



upload-package:
  extends:
    - .upload-package
  rules:
    - if: '$CI_COMMIT_TAG'


upload-package-manual:
  when: manual
  extends:
    - .upload-package


# Tag the current image with a name that triggers automatic deploy
tag-image-for-production:
  stage: deploy
  image: docker:dind
  services:
    - docker:dind
  tags:
    - inasset
    - dind
  variables:
    TAG: $CI_REGISTRY/wjs/yakunin-project/yakunin:$YAKUNIN_PRODUCTION
    TAG_PRODUCTION: $CI_REGISTRY/wjs/yakunin-project/yakunin:production
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $TAG
    - docker tag $TAG $TAG_PRODUCTION
    - docker push $TAG_PRODUCTION
  rules:
   - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
     when: always
   - if: $CI_PIPELINE_SOURCE == "schedule"
     when: always
