services:
  redis:
    image: "redis:alpine"
    pull_policy: weekly


  yakunin:
    build:
      dockerfile: Dockerfile.base
      # TODO: allow for cache
      # cache_to:
      #   - type=local,dest=/tmp/cache
      # cache_from:
      #   - type=local,src=/tmp/cache

    # NB: to avoid building locally, one can
    # - use the pipeline to run the job "build-commit-image"
    # - uncomment the following line, setting the correct commit (short) SHA
    # image: registry.gitlab.sissamedialab.it/wjs/yakunin-project/yakunin:5b01d9b
    ports:
      - "1235:8889"
    environment:
      REDIS_HOST: redis
      DEBUG: "True"
    depends_on:
      - "redis"
