services:
  redis:
    image: "redis:alpine"
    pull_policy: weekly

  yakunin:
    image: registry.gitlab.sissamedialab.it/wjs/yakunin-project/yakunin:production
    ports:
      - "1235:8889"
    environment:
      REDIS_HOST: redis
    depends_on:
      - "redis"
