# To be generated ad necessitam (?) when medialab-sty changes
# To be generated manually, e.g. when medialab-sty changes
# This image can be used as a base for the daily debian updates
# See also CI variables
ARG ML_VERSION="trixie-tl25-py313-ml2"
FROM registry.gitlab.sissamedialab.it/calderan/medialab-sty/medialab-sty:$ML_VERSION
LABEL mantainer="wjs-support@medialab.sissa.it>"

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    --mount=type=cache,target=/root/.cache/pip

RUN apt-get update && \
    apt-get install -y pdftk imagemagick xpdf libreoffice file && \
    libreoffice --headless --terminate_after_init

COPY . /workdir
RUN groupadd -g 1000 app && \
  useradd --no-log-init --uid 1000 --gid app -m --home-dir /home/app app && \
  chown -R app:app /workdir
ENV PATH="/home/app/.local/bin:${PATH}"
USER app
WORKDIR /workdir
RUN pip install --extra-index-url=https://gitlab.sissamedialab.it/api/v4/projects/60/packages/pypi/simple --break-system-packages .[service,test]

CMD ["yakunin-start"]
