# This image can be used as a base for the daily debian updates
# See also CI variables
ARG ML_VERSION="trixie-tl25-py313-ml2"
FROM registry.gitlab.sissamedialab.it/wjs/yakunin-project/requirements:$ML_VERSION
LABEL mantainer="wjs-support@sissamedialab.it>"

COPY --chown=app:app . /workdir
RUN --mount=type=cache,target=/home/app/.cache/pip,uid=1000,gid=1000 \
    pip install \
    --break-system-packages \
    --cache-dir /home/app/.cache/pip \
    --extra-index-url=https://gitlab.sissamedialab.it/api/v4/projects/60/packages/pypi/simple \
    .[service,test]

ENV DJANGO_SETTINGS_MODULE="yakunin_service.settings"
# Do not buffer python, or we don't get some log messages where we expect them.
ENV PYTHONUNBUFFERED="1"
CMD ["daphne",  "-b", "0.0.0.0", "-p",  "8889",  "yakunin_service.asgi:application"]
